replace DistrictName =	"Visakhapatnam"	if DistrictName ==	"Alluri Sitharama Raju"	& StateName ==	"Andhra Pradesh"
replace DistrictName =	"Visakhapatnam"	if DistrictName ==	"Anakapalli"	& StateName ==	"Andhra Pradesh"
replace DistrictName =	"Y.S.R. (Cuddapah)"	if DistrictName ==	"Annamayya"	& StateName ==	"Andhra Pradesh"
replace DistrictName =	"Guntur"	if DistrictName ==	"Bapatla"	& StateName ==	"Andhra Pradesh"
replace DistrictName =	"Guntur"	if DistrictName ==	"Dr. Br Ambedkar Konaseema"	& StateName ==	"Andhra Pradesh"
replace DistrictName =	"West Godavari"	if DistrictName ==	"Eluru"	& StateName ==	"Andhra Pradesh"
replace DistrictName =	"East Godavari"	if DistrictName ==	"Kakinada"	& StateName ==	"Andhra Pradesh"
replace DistrictName =	"Kurnool"	if DistrictName ==	"Nandyal"	& StateName ==	"Andhra Pradesh"
replace DistrictName =	"Krishna"	if DistrictName ==	"Ntr"	& StateName ==	"Andhra Pradesh"
replace DistrictName =	"Guntur"	if DistrictName ==	"Palnadu"	& StateName ==	"Andhra Pradesh"
replace DistrictName =	"Vizianagaram"	if DistrictName ==	"Parvathipuram Manyam"	& StateName ==	"Andhra Pradesh"
replace DistrictName =	"Anantapur"	if DistrictName ==	"Sri Satya Sai"	& StateName ==	"Andhra Pradesh"
replace DistrictName =	"Nellore"	if DistrictName ==	"Tirupathi"	& StateName ==	"Andhra Pradesh"
replace DistrictName =	"West Siang"	if DistrictName ==	"Lepa Rada"	& StateName ==	"Arunachal Pradesh"
replace DistrictName =	"Tirap"	if DistrictName ==	"Longding"	& StateName ==	"Arunachal Pradesh"
replace DistrictName =	"West Siang"	if DistrictName ==	"Lower Siang"	& StateName ==	"Arunachal Pradesh"
replace DistrictName =	"Lohit"	if DistrictName ==	"Namsai"	& StateName ==	"Arunachal Pradesh"
replace DistrictName =	"West Siang"	if DistrictName ==	"Shi Yomi"	& StateName ==	"Arunachal Pradesh"
replace DistrictName =	"East Siang"	if DistrictName ==	"Siang"	& StateName ==	"Arunachal Pradesh"
replace DistrictName =	"North East"	if DistrictName ==	"Shahdara"	& StateName ==	"Delhi"
replace DistrictName =	"South"	if DistrictName ==	"South East Delhi"	& StateName ==	"Delhi"
replace DistrictName =	"Bhiwani"	if DistrictName ==	"Charkhi Dadri"	& StateName ==	"Haryana"
replace DistrictName =	"Bellary"	if DistrictName ==	"Vijayanagara"	& StateName ==	"Karnataka"
replace DistrictName =	"Shajapur"	if DistrictName ==	"Agar Malwa"	& StateName ==	"Madhya Pradesh"
replace DistrictName =	"Tikamgarh"	if DistrictName ==	"Niwari"	& StateName ==	"Madhya Pradesh"
replace DistrictName =	"Thane"	if DistrictName ==	"Palghar"	& StateName ==	"Maharashtra"
replace DistrictName =	"Imphal East"	if DistrictName ==	"Jiribam"	& StateName ==	"Manipur"
replace DistrictName =	"Thoubal"	if DistrictName ==	"Kakching"	& StateName ==	"Manipur"
replace DistrictName =	"Senapati"	if DistrictName ==	"Kangpokpi"	& StateName ==	"Manipur"
replace DistrictName =	"Chandel"	if DistrictName ==	"Tengnoupal"	& StateName ==	"Manipur"
replace DistrictName =	"Jaintia Hills"	if DistrictName ==	"East Jaintia Hills"	& StateName ==	"Meghalaya"
replace DistrictName =	"West Khasi Hills"	if DistrictName ==	"Eastern West Khasi Hills"	& StateName ==	"Meghalaya"
replace DistrictName =	"East Garo Hills"	if DistrictName ==	"North Garo Hills"	& StateName ==	"Meghalaya"
replace DistrictName =	"West Garo Hills"	if DistrictName ==	"South West Garo Hills"	& StateName ==	"Meghalaya"
replace DistrictName =	"West Khasi Hills"	if DistrictName ==	"South West Khasi Hills"	& StateName ==	"Meghalaya"
replace DistrictName =	"Jaintia Hills"	if DistrictName ==	"West Jaintia Hills"	& StateName ==	"Meghalaya"
replace DistrictName =	"Dimapur"	if DistrictName ==	"Chumukedima"	& StateName ==	"Nagaland"
replace DistrictName =	"Dimapur"	if DistrictName ==	"Niuland"	& StateName ==	"Nagaland"
replace DistrictName =	"East District"	if DistrictName ==	"Gangtok District"	& StateName ==	"Sikkim"
replace DistrictName =	"West District"	if DistrictName ==	"Gyalshing District"	& StateName ==	"Sikkim"
replace DistrictName =	"North District"	if DistrictName ==	"Mangan District"	& StateName ==	"Sikkim"
replace DistrictName =	"South District"	if DistrictName ==	"Namchi District"	& StateName ==	"Sikkim"
replace DistrictName =	"East District"	if DistrictName ==	"Pakyong District"	& StateName ==	"Sikkim"
replace DistrictName =	"West District"	if DistrictName ==	"Soreng District"	& StateName ==	"Sikkim"
replace DistrictName =	"Kancheepuram"	if DistrictName ==	"Chengalpattu"	& StateName ==	"Tamil Nadu"
replace DistrictName =	"Viluppuram"	if DistrictName ==	"Kallakkurichi"	& StateName ==	"Tamil Nadu"
replace DistrictName =	"Nagapattinam"	if DistrictName ==	"Mayiladuthurai"	& StateName ==	"Tamil Nadu"
replace DistrictName =	"Vellore"	if DistrictName ==	"Ranipet"	& StateName ==	"Tamil Nadu"
replace DistrictName =	"Tirunelveli"	if DistrictName ==	"Tenkasi"	& StateName ==	"Tamil Nadu"
replace DistrictName =	"Vellore"	if DistrictName ==	"Tirupattur"	& StateName ==	"Tamil Nadu"
replace DistrictName =	"Sultanpur"	if DistrictName ==	"Amethi"	& StateName ==	"Uttar Pradesh"
replace DistrictName =	"Panchsheel nagar"	if DistrictName ==	"Hapur"	& StateName ==	"Uttar Pradesh"
replace DistrictName =	"Moradabad"	if DistrictName ==	"Sambhal"	& StateName ==	"Uttar Pradesh"
replace DistrictName =	"Muzaffarnagar"	if DistrictName ==	"Shamli"	& StateName ==	"Uttar Pradesh"
