* TUS TO PLFS

replace StateName =	"A & N Island"	if StateName==	"A & N Islands"
replace StateName =	"Uttrakhand"	if StateName==	"Uttarakhand"


replace DistrictName=	"Sabar Kantha"	if DistrictName==	"Arvalli"	& StateName==	"Gujarat"
replace DistrictName=	"Bhavnagar"	if DistrictName==	"Botad"	& StateName==	"Gujarat"
replace DistrictName=	"Vadodara"	if DistrictName==	"Chhota Udepur"	& StateName==	"Gujarat"
replace DistrictName=	"Jamnagar"	if DistrictName==	"DevBhumi-Dwarka"	& StateName==	"Gujarat"
replace DistrictName=	"Junagadh"	if DistrictName==	"Gir Somnath"	& StateName==	"Gujarat"
replace DistrictName=	"Panch Mahals"	if DistrictName==	"Mahisagar"	& StateName==	"Gujarat"
replace DistrictName=	"Rajkot"	if DistrictName==	"Morbi"	& StateName==	"Gujarat"
replace DistrictName=	"Leh (Ladakh)"	if DistrictName==	"Leh"	& StateName==	"Jammu & Kashmir"
replace DistrictName=	"Ganganagar"	if DistrictName==	"Sri Ganganagar"	& StateName==	"Rajasthan"
replace DistrictName=	"Khammam"	if DistrictName==	"Bhadradri"	& StateName==	"Telangana"
replace DistrictName=	"Karimnagar"	if DistrictName==	"Jagtial"	& StateName==	"Telangana"
replace DistrictName=	"Warangal"	if DistrictName==	"Jangaon"	& StateName==	"Telangana"
replace DistrictName=	"Warangal"	if DistrictName==	"Jayashankar"	& StateName==	"Telangana"
replace DistrictName=	"Mahbubnagar"	if DistrictName==	"Jogulamba"	& StateName==	"Telangana"
replace DistrictName=	"Nizamabad"	if DistrictName==	"Kamareddy"	& StateName==	"Telangana"
replace DistrictName=	"Adilabad"	if DistrictName==	"Komaram Bheem"	& StateName==	"Telangana"
replace DistrictName=	"Warangal"	if DistrictName==	"Mahabubabad"	& StateName==	"Telangana"
replace DistrictName=	"Adilabad"	if DistrictName==	"Mancherial"	& StateName==	"Telangana"
replace DistrictName=	"Rangareddy"	if DistrictName==	"Medchal-Malkajgiri"	& StateName==	"Telangana"
replace DistrictName=	"Mahbubnagar"	if DistrictName==	"Nagarkurnool"	& StateName==	"Telangana"
replace DistrictName=	"Adilabad"	if DistrictName==	"Nirmal"	& StateName==	"Telangana"
replace DistrictName=	"Karimnagar"	if DistrictName==	"Peddapalli"	& StateName==	"Telangana"
replace DistrictName=	"Karimnagar"	if DistrictName==	"Rajanna"	& StateName==	"Telangana"
replace DistrictName=	"Medak"	if DistrictName==	"Sangareddy"	& StateName==	"Telangana"
replace DistrictName=	"Medak"	if DistrictName==	"Siddipet"	& StateName==	"Telangana"
replace DistrictName=	"Nalgonda"	if DistrictName==	"Suryapet"	& StateName==	"Telangana"
replace DistrictName=	"Rangareddy"	if DistrictName==	"Vikarabad"	& StateName==	"Telangana"
replace DistrictName=	"Mahbubnagar"	if DistrictName==	"Wanaparthy"	& StateName==	"Telangana"
replace DistrictName=	"Warangal"	if DistrictName==	"Warangal Rural"	& StateName==	"Telangana"
replace DistrictName=	"Warangal"	if DistrictName==	"Warangal Urban"	& StateName==	"Telangana"
replace DistrictName=	"Nalgonda"	if DistrictName==	"Yadadri"	& StateName==	"Telangana"
replace DistrictName=	"Jalpaiguri"	if DistrictName==	"Alipurduar"	& StateName==	"West Bengal"
replace DistrictName=	"Paschim Medinipur"	if DistrictName==	"Jhargram"	& StateName==	"West Bengal"
replace DistrictName=	"Darjiling"	if DistrictName==	"Kalimpong"	& StateName==	"West Bengal"
replace DistrictName=	"Barddhaman"	if DistrictName==	"Paschim Barddhaman"	& StateName==	"West Bengal"
replace DistrictName=	"Barddhaman"	if DistrictName==	"Purba Barddhaman"	& StateName==	"West Bengal"
